[package]
name = "rust_interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = { version = "7.4.0", features = ["fancy"] }
clap = { version = "4.5.16", features = ["derive"] }
thiserror = "1.0.63"
bytes = "1.3.0"